name = "digital-garden-v2"
compatibility_date = "2024-04-03"
main = "src/worker.ts"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[vars]
NODE_VERSION = "20"

[build]
command = "npm run build"

[[routes]]
pattern = "subsurfaces.net"
custom_domain = true

[[routes]]
pattern = "www.subsurfaces.net"
custom_domain = true

[[routes]]
pattern = "wiki.subsurfaces.net"
custom_domain = true

[[routes]]
pattern = "chat.subsurfaces.net"
custom_domain = true
